# Generated by Django 4.1.6 on 2023-10-12 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('payload', models.TextField()),
                ('output', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='checklist',
        ),
        migrations.RenameField(
            model_name='checklist',
            old_name='name',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='ChecklistItem',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='testresult',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.checklist'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='checklist_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.checklistpoint'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.website'),
        ),
        migrations.AddField(
            model_name='checklistpoint',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.checklist'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checklist.website'),
        ),
    ]
