# Generated by Django 4.1.6 on 2023-10-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_remove_result_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterchecklist',
            name='payload',
            field=models.TextField(blank=True),
        ),
    ]
